version: '3.8'
services:
    main:
        build: .
        ports:
            - '80:3000'
        restart: always

    signin-1:
        build: web-challenges/signin-form-1
        ports:
            - '3000:80'
        restart: always

    password-reset-1:
        build: web-challenges/password-reset-1
        ports:
            - '3001:80'
        restart: always
